---
title: "Assignment2A_Approach"
author: "Cecilia De La Fuente Chavez"
format: html
editor: visual
---

## Approach Deliverable

### Overview

For Assignment 2A, I used Rotten Tomatoes' article titled "[30 Most Popular Movies Right Now: What to Watch In Theaters and Streaming](https://editorial.rottentomatoes.com/guide/popular-movies/)" to choose six movies currently in theaters; *The Odyssey, Spider-Man: Brand New Day, Tony, Obsession, The Dog Stars, and Coyote vs. ACME.* I created a [simple survey](https://forms.cloud.microsoft/r/JqecqrN0jp) asking respondents to rate each of the movies they have seen from the list and to select "Have not seen it." if they haven't. To ensure data completeness each response is required, but the survey should only take about 30 seconds to fill out to avoid survey fatigue. Once responses have been collected I will design the SQL tables and start the analysis. The main problem I anticipate is low survey participation and a high volume of "Have not seen it." responses which could limit the analysis.
